### ISSUE TITLE
[QUESTION] Can I customize running actions?

### ISSUE THREAD

**Issue by michaelmuselik** [Foulest/RepairKit#14]
Hi, thanks for hard work. Perfect piece of useful software.
I have one practical question.
Can I somehow influence which applications to keep, which to remove, which services to keep, which to stop? I would like to customize the individual steps.
But I don't want to tamper with the source code, I'm not a hard code programmer.
THNX, Michael

**Comment by Foulest** [comment]
I'll make the changes required to do this ASAP.

**Comment by michaelmuselik** [comment]
> I'll make the changes required to do this ASAP.

Thank you very much and respectfully 👍 .

**Comment by Foulest** [comment]
I have made significant changes to the automatic repair process! Every step of the way is completely configurable - although, it's only recommended to change it if you know what you are doing.

**Comment by Foulest** [comment]
Let me know how you like them. Hardly anything is hard-coded anymore! @michaelmuselik

**Comment by michaelmuselik** [comment]
> Let me know how you like them. Hardly anything is hard-coded anymore! @michaelmuselik

@Foulest Thanks a Lot. Great work. 👍 
Last thing. Can I check only some items, I thing only some areas of repair?

![image](https://github.com/user-attachments/assets/2f1de054-e2f6-4c4b-8fc6-700bfa08a7cc)

**Comment by Foulest** [comment]
Unfortunately, those checks aren't functional in that way. They just update the steps as they go along. If you want to disable certain steps, set the 'enabled' flags to 'false' in the config files.

**Comment by michaelmuselik** [comment]
> Unfortunately, those checks aren't functional in that way. They just update the steps as they go along. If you want to disable certain steps, set the 'enabled' flags to 'false' in the config files.

I understand. OK. Thank you 🥇
