### ISSUE TITLE
1.20, 1.2.1 will not work after detection on windows defender

### ISSUE THREAD

**Issue by heiesd** [Foulest/RepairKit#18]
Hello foulest,

first: perhaps my englich is not perfect.
since 1.2.0 repairkit ist not working anymore in the modul "automatic repairs. the same in 1.2.1. 
1.1.9 works.
Background: 1.2.0 was recognized by windows defender as a trojan and had been blocked. I tried again and clicked on "allow this program on my computer". Now the program starts - but did not work on automatic repairs. the items will not be checked
[RepairKit.log](https://github.com/user-attachments/files/17145811/RepairKit.log)
.
This are the last notifications in the log:
[10:44:34.468657900] Running Automatic Repairs...
[10:44:34.468657900] Disabling the run button...
[10:44:34.471060500] Checking if the operating system is outdated...
[10:44:34.471060500] Creating a restore point...
[10:44:34.471671400] Running command: wmic.exe /Namespace:\\root\default Path SystemRestore Call CreateRestorePoint "RepairKit Automatic Repairs", 100, 7
[10:44:44.130740800] Deleting system policies...
[10:44:44.200999400] Deleting registry key: SOFTWARE\Policies\Microsoft\MMC
[10:44:44.264518200] Deleting registry key: SOFTWARE\Policies\Microsoft\Windows\System
[10:44:44.265518300] Deleting registry key: SOFTWARE\Policies\Google\Chrome

after this the log stopped.

Any Idea, how to fix it?

**Comment by Foulest** [comment]
What do you mean, Windows Defender recognizes RepairKit as a trojan?

Also, try replacing your policies.json file with this one and send me a new log file.
[policies.json](https://github.com/user-attachments/files/17152975/policies.json)

**Comment by Foulest** [comment]
Try running the linked version of RepairKit and send the log file.

https://www.dropbox.com/scl/fi/2ypl1sez10j8vts9ais19/RepairKit-1.2.1.zip?rlkey=y4xpdab7lwcruyv8zjgkz76dp&st=08t48p6w&dl=0

**Comment by heiesd** [comment]
[RepairKit.log](https://github.com/user-attachments/files/17161395/RepairKit.log)

I've tried your linked version - it does'nt work :-(

**Comment by Foulest** [comment]
Try running this instead. Extract the ZIP file and run the `start.bat` file. It will open RepairKit. Run the Automatic Repairs. Give it a few seconds, and if you notice it still not working, close it. A `RepairKit.log` file should be in the `jre\bin` folder. Send that. Hopefully now we'll get this fixed.

https://www.dropbox.com/scl/fi/71ws397x3ynnxviim3iis/RepairKit.zip?rlkey=6t4eye1vfy25pptwnmcf5efk7&st=c1ucn5c4&dl=1

**Comment by heiesd** [comment]
no, unfortunately not, think that something is blocked since the first (false) detection by Defender. 
as I said, since then your versions are no longer recognized as a virus, not even your bat file, which deletes a lot of registry entries.
[RepairKit.log](https://github.com/user-attachments/files/17173601/RepairKit.log)

**Comment by Foulest** [comment]
Thanks for trying. It appears that, when trying to delete the Google Chrome registry key, it locks up without throwing an exception. After ruling out all options, the fix is simple. Attached is a preview version that should work. Thanks for helping debug this. Of course, after running, send the log file in %temp%\RepairKit.log. But, it should work.

https://www.dropbox.com/scl/fi/j219uy1om8ixlyob7ijza/RepairKit-1.2.2-PREVIEW.zip?rlkey=omxf9dh6ba01n2hu09d0ayzu1&st=r2k6zdq9&dl=1

**Comment by heiesd** [comment]
Hurray, it works!
Thank you for your many attempts, your patience and last but not least for the solution!
The only point that has not been checked off is “run registry tweaks”.
Best regards
heiesd
[RepairKit.log](https://github.com/user-attachments/files/17178582/RepairKit.log)

**Comment by Foulest** [comment]
[registry.json](https://github.com/user-attachments/files/17178604/registry.json)
Try replacing your registry.json file with that one and send a new log file. :)

**Comment by heiesd** [comment]
now it's perfect ;-)
[RepairKit.log](https://github.com/user-attachments/files/17178662/RepairKit.log)

**Comment by Foulest** [comment]
Great! Who knew Chrome and Adobe registry keys would break everything? Shipping global update ASAP.
