### ISSUE TITLE
What exactly "Automatic repairs" do??? Can we have a "Manual" option?

### ISSUE THREAD

**Issue by BlueDrakoPT** [Foulest/RepairKit#9]
**Before you submit this question, please make sure you have done the following:**

- [ ] I have checked the existing documentation for this project
- [ ] I have searched the issue tracker for a similar question

**Your Question**
Write your question here. Please provide as much detail as possible.

**Additional context**
Add any other context or screenshots about the question here.

**Comment by Foulest** [comment]
I've added a detailed section to the new Wiki page, [which you can find here](https://github.com/Foulest/RepairKit/wiki/Automatic-Repairs). It should answer all of your questions about the Automatic Repair process. And no, there is no and will be no manual mode.
